### ISSUE TITLE
Update Content

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cvp#1]
In the "What is ...." box on the home page can you replace it to read:
C.V.P is a product of United Learning Foundation (www.ULFUSA.com); an in-demand consulting firm that provides high quality trainings for all employees that interface with the general public on how to best serve those that live with unseen challenges (disabilities).

The Compassionate Vendor Program is a third-party certification that is officially recognized by the United States federal government. Each institution that chooses to train its employees on how to reach every customer and create a more inclusive, compassionate, and empathetic environment for people of all abilities, as well as meeting all other set criteria, will be certified through the Compassionate Vendor Program. Upon completion of the program only these businesses may proudly display the C.V.P. certification logo as a way to publicly acknowledge their commitment to their community, as well as be listed in this on-line directory.

Certification through the Compassionate Vendor Program is the gold standard in customer service.

Also: on the FAQ page, under Are There Any Requirements?
Can you capitalize the word If (first word of the second sentence)?

Make these changes on master and gh-pages and then upload to FTP as well please.

due: 
8-21-15   5p

**Comment by AaronAguilar** [comment]
Updated content - http://editllc.github.io/client-cvp/
