### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cvp#2]
Replace the logo with the one attached here. 

The difference is that this logo has the "TM" on it. 

![cvp-logo](https://cloud.githubusercontent.com/assets/539962/9397446/919fb454-4751-11e5-8af3-328339e7753a.jpg)

due:
8-21-15  4p

**Comment by AaronAguilar** [comment]
Updated - http://editllc.github.io/client-cvp/

Uploading to the FTP now .

**Comment by AaronAguilar** [comment]
It's live and updated: http://www.cvpglobal.com/
