### ISSUE TITLE
Changes to the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cvp#3]
1) On the FAQ page, under "What Do We Really...", it mentions that the certification is good for 5 years. Can you change that to read "three"?

2) Change the title of the "Government Offices" page to read "Government Agencies". I am training a lot of transit/bus drivers, and while they're an agency, they're not necessarily an "office". :)

3) NEW LISTING!!! (wooohoooo!)
Page: Government Agency
to read:
City of Clovis (CA) Transit
exp. 10/2018

due:
11-18-15   3p

**Comment by rodneystrong** [comment]
The domain name in our FTP should be cvpglobal.com

**Comment by rodneystrong** [comment]
A video I made figuring it out: http://somup.com/coXqVCYue

You should be able to deduce how to recreate this for a different property for each listing and then have it display.

**Comment by rampage1213** [comment]
Done! Great learning experience!
